---
## https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
## https://github.com/ansible/ansible/issues/5241
## https://gist.github.com/manuelmeurer/a2c0a8c24a0bb5092250
## https://github.com/kamaln7/ansible-swapfile

- name: Check if swap file exists
  ansible.builtin.stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: Create swap space - debian
  # ansible.builtin.command: "dd if=/dev/zero of={{ swap_file }} bs=1M count={{ swap_size }}"
  ansible.builtin.command: "fallocate -l {{ swap_size }}M {{ swap_file }}"
  when: not swap_file_check.stat.exists and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  # when: ansible_swaptotal_mb < 1 and not swap_file_check.stat.exists
  # when: ansible_swaptotal_mb < 1

## https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-centos-7?comment=31159
## https://www.linux.com/forums/lfs201-class-forum/lab-131-swapon-failed-invalid-argument
- name: Create swap space - redhat  # noqa no-free-form
  ansible.builtin.command: "dd if=/dev/zero of={{ swap_file }} bs=1M count={{ swap_size }}"
  when: not swap_file_check.stat.exists and ansible_os_family == "RedHat"

- name: Make swap
  ansible.builtin.command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists
  # when: ansible_swaptotal_mb < 1 and not swap_file_check.stat.exists

- name: Change swap file permissions
  ansible.builtin.file:
    path: "{{ swap_file }}"
    owner: root
    group: root
    mode: 0600

- name: Add to fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"
    mode: 0644
    state: present

- name: Debug | ansible_virtualization_type
  ansible.builtin.debug:
    var: ansible_virtualization_type
- name: Not container
  when: >
    (ansible_virtualization_type is not defined or
      (ansible_virtualization_type != "lxc" and ansible_virtualization_type != "docker")
    )
  block:
    - name: Turn swap on
      ansible.builtin.command: swapon -a
      when: not swap_file_check.stat.exists

    - name: Check current swappiness value
      ansible.builtin.command: cat /proc/sys/vm/swappiness
      changed_when: false
      register: proc1
    - name: Set swappiness (proc)
      ansible.builtin.shell: "echo {{ swap_swappiness | string }} | tee /proc/sys/vm/swappiness"
      when: proc1 is defined and proc1.stdout != swap_swappiness | string

    - name: Set swappiness (sysctl)
      ansible.posix.sysctl:
        name: vm.swappiness
        value: "{{ swap_swappiness | string }}"

    - name: Check current vfs_cache_pressure value
      ansible.builtin.command: cat /proc/sys/vm/vfs_cache_pressure
      changed_when: false
      register: proc2
    - name: Set vfs_cache_pressure (proc)
      ansible.builtin.shell: echo 50 | tee /proc/sys/vm/vfs_cache_pressure
      when: proc2 is defined and proc2.stdout != "50"

    - name: Set vm.vfs_cache_pressure (sysctl)
      ansible.posix.sysctl:
        name: vm.vfs_cache_pressure
        value: "50"
